### ISSUE TITLE
Increase scale-up limit

### ISSUE THREAD

**Issue by gaydenko** [sjoerdvankreel/firefly-synth#2]
Hi,

Thanks for Linux support. I have tired FF as VST3 plugin in REAPER (built from AUR). A KDE (EndeavourOS, Arch-based) is in use with 4k monitor and 200% as a system scaling. When I change (increase) plugin window size, I  run into limitation (no more increasing), but got maximum size still isn't sufficiently large for my not too young eyes (and 27" monitor).

Would you please increase scaling-up limit?

**Comment by sjoerdvankreel** [comment]
Hey.

>> Thanks for Linux support.

Appreciated. Glad to see people are actually using this.

>> Would you please increase scaling-up limit

This branch https://github.com/sjoerdvankreel/firefly-synth/tree/increase-max-ui-scaling changes the scale limit from 200 to 800%. It's a really simple fix but like i said i cannot test it at home, because small monitor. Would you be willing to test it for me? Being a Linux user I assume you can build from source, but if not, I can upload binaries somewhere for you to test.

**Comment by gaydenko** [comment]
> changes the scale limit from 200 to 800%

Yes, it does work for me, thanks.



> Being a Linux user I assume you can build from source

Yes, with help of some old knowledge I was able to build and try. But I'd not hope all Linux users are ready to build from source. Modern Linux distro are much more friendly to not technically inclined users.

**Comment by sjoerdvankreel** [comment]
>> Yes, it does work for me, thanks.

Great! Thanks for testing.

>> Modern Linux distro are much more friendly to not technically inclined users.

This is true. I do provide binaries for linux, although not for every bugfix. Not for windows either btw. I've merged into main. Binary releases will get picked up on the next "major" update. Thanks for reporting!
